name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        run: g++ -std=c++17 -o powerset powerset.cpp

      - name: Run
        run: ./powerset
